CREATE TABLE IF NOT EXISTS Qualifications(
		Id INTEGER PRIMARY KEY AUTOINCREMENT,
		WorkerId INTEGER,
		CertName TEXT NOT NULL,
		IsActive BOOLEAN NOT NULL,
		FOREIGN KEY (WorkerId) REFERENCES workers(Id) ON DELETE CASCADE );