CREATE TABLE IF NOT EXISTS Workers (
		Id INTEGER PRIMARY KEY AUTOINCREMENT,
		Name TEXT NOT NULL,
		DateCreated DATETIME NOT NULL,
		IsActive BOOLEAN NOT NULL,
		Position TEXT NOT NULL,
		Salary REAL NOT NULL,
		BirthDate DATETIME NOT NULL,
		Gender TEXT NOT NULL,
		Degree TEXT NOT NULL,
		JobDescription TEXT NOT NULL );